config/routes.rb
Rails.application.routes.draw do
  resources :labels
  namespace :admin do
    resources :users
  end
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :tasks, dependent: :destroy
    before_destroy do
      throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
    end
    before_update do
      throw(:abort) if User.where(admin: true).count <= 1 && self.admin?
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user), notice: "ユーザ「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザ「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザ「#{@user.name}」を削除しました。"
    else
      redirect_to admin_users_path, notice: '管理者ユーザー数は0にはできません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin, :name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/users_controller.rb
    class UsersController < ApplicationController
        skip_before_action :login_required, only: [:new, :create]
        before_action :set_current_user
        before_action :ensure_current_user, {only: [:show]}
        before_action :not_ensure_current_user, {only: [:new]}   
        def new
            @user = User.new #newページを生成
        end
        def create
            @user = User.new(user_params)
            if @user.save
              session[:user_id] = @user.id
              redirect_to user_path(@user.id)
            else
              render :new
            end
        end
        def show
            @user = User.find(params[:id])
        end
        private
        def user_params
            params.require(:user).permit(:name,:email,:password,
                                         :password_confirmation)#permitで指定しているシンボルのパラメータのみデータ送信を許可
        end
        def ensure_current_user
            if @current_user.id != params[:id].to_i
                flash[:notice]="権限がありません"
                redirect_to tasks_path
            end
        end
        def not_ensure_current_user
            if @current_user
                flash[:notice]="ログインしています"
                redirect_to tasks_path
            end
        end
    end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin,@user], local: true do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  <%= form.label :admin %>
  <%= form.select :admin, [["無効", false], ["有効", true]] %>
  <br>
  <%= form.submit "Create User" %>
<% end %>

app/views/admin/users/edit.html.erb
<h1 class="mt-5 pt-5">ユーザー編集</h1>
<%= form_with model: [:admin,@user], local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.label :admin %>
  <%= form.select :admin, [["無効", false], ["有効", true]] %>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  <br>
  <%= form.submit "Create User" %>
<% end %>
<%= link_to 'Show', @user %>
<%= link_to '戻る', admin_users_path %>

app/views/admin/users/index.html.erb
<h1 class="mt-5 pt-5">ユーザ一管理</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th class=>Tasks_counts</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, admin_user_path(user)%></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <th><%= user.tasks.count %></th>
        <td><%= link_to '編集する',edit_admin_user_path(user) %></td>
        <td><%= link_to '削除する',[:admin, user], method: :delete, data:{ confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= link_to 'userを新規作成する', new_admin_user_path %>

app/views/admin/users/new.html.erb
<div class="container">
<h1 class="mt-5 pt-5">Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name, '名前' %>
  <%= f.text_field :name, class:'form-control' %>
  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email, class:'form-control'%>
  <%= f.label :password, 'パスワード'%>
  <%= f.password_field :password, class:'form-control' %>
  <%= f.label :password_confirmation,'パスワード（確認）' %>
  <%= f.password_field :password_confirmation, class:'form-control'%>
  <%= f.submit "Create account",class:'btn btn-primary' %>
<% end %>
</div>

app/views/admin/users/show.html.erb
<h4 class="mt-5 pt-5"><strong><%= @user.name + "のページ" %></strong></h4>
<div>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>詳細</th>
      <th>終了期限</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <td><%= task.details %></td>
        <td><%= task.limit %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to 'userを編集する',edit_admin_user_path(@user) %>
<br>
<%= link_to 'userを削除する',[:admin, @user], method: :delete, data:{ confirm: '本当に削除していいですか？' } %>