config/routes.rb
Rails.application.routes.draw do
  resources :labels
  namespace :admin do
    resources :users
  end
  get 'sessions/new'
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="">
      <ul class="">
        <li class="head text-white text-left"><h5>Task_Management</h5></li>
        <li class="head text-white "><%= link_to 'タスクを作る', new_task_path %></li>
        <li class="head text-white "><%= link_to 'ラベルを作る', labels_path %></li>
        <li class="head text-white "><%= link_to 'タスク一覧', tasks_path %></li>
        <% if logged_in? %>
          <li class="head text-white "><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li class="head text-white "><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% if @current_user.admin%>
            <li class="head text-white "><%= link_to "ユーザー一覧画面", admin_users_path %></li>
          <% end %>
        <% else %>
          <li class="head text-white "><%= link_to "アカウント作成", new_user_path %></li>
          <li class="head text-white "><%= link_to "ログイン", new_session_path %></li>
        <% end %>
      </ul> 
    </header>
    <div class="mt-5 pt-5">
     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  <%= yield %>
  </body>
</html>